"""empty message

Revision ID: 2189ff368dff
Revises: 
Create Date: 2023-04-24 21:30:49.030996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2189ff368dff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_matches')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant1_summoner_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant2_summoner_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant3_summoner_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant4_summoner_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant5_summoner_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant6_summoner_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant7_summoner_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant8_summoner_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant9_summoner_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant10_summoner_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant1_champion_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant2_champion_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant3_champion_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant4_champion_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant5_champion_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant6_champion_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant7_champion_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant8_champion_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant9_champion_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant10_champion_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant1_team_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant2_team_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant3_team_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant4_team_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant5_team_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant6_team_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant7_team_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant8_team_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant9_team_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('participant10_team_id', sa.String(), nullable=True))
        batch_op.drop_column('participant_champion_names')
        batch_op.drop_column('participant_summoner_names')
        batch_op.drop_column('participant_team_ids')

    with op.batch_alter_table('summoners', schema=None) as batch_op:
        batch_op.create_unique_constraint("summoner_puuid_unique", ['summoner_puuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summoners', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_team_ids', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('participant_summoner_names', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('participant_champion_names', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('participant10_team_id')
        batch_op.drop_column('participant9_team_id')
        batch_op.drop_column('participant8_team_id')
        batch_op.drop_column('participant7_team_id')
        batch_op.drop_column('participant6_team_id')
        batch_op.drop_column('participant5_team_id')
        batch_op.drop_column('participant4_team_id')
        batch_op.drop_column('participant3_team_id')
        batch_op.drop_column('participant2_team_id')
        batch_op.drop_column('participant1_team_id')
        batch_op.drop_column('participant10_champion_name')
        batch_op.drop_column('participant9_champion_name')
        batch_op.drop_column('participant8_champion_name')
        batch_op.drop_column('participant7_champion_name')
        batch_op.drop_column('participant6_champion_name')
        batch_op.drop_column('participant5_champion_name')
        batch_op.drop_column('participant4_champion_name')
        batch_op.drop_column('participant3_champion_name')
        batch_op.drop_column('participant2_champion_name')
        batch_op.drop_column('participant1_champion_name')
        batch_op.drop_column('participant10_summoner_name')
        batch_op.drop_column('participant9_summoner_name')
        batch_op.drop_column('participant8_summoner_name')
        batch_op.drop_column('participant7_summoner_name')
        batch_op.drop_column('participant6_summoner_name')
        batch_op.drop_column('participant5_summoner_name')
        batch_op.drop_column('participant4_summoner_name')
        batch_op.drop_column('participant3_summoner_name')
        batch_op.drop_column('participant2_summoner_name')
        batch_op.drop_column('participant1_summoner_name')

    op.create_table('_alembic_tmp_matches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('summoner_puuid', sa.VARCHAR(), nullable=True),
    sa.Column('match_id', sa.VARCHAR(), nullable=True),
    sa.Column('champion_name', sa.VARCHAR(), nullable=True),
    sa.Column('win', sa.INTEGER(), nullable=True),
    sa.Column('kills', sa.FLOAT(), nullable=True),
    sa.Column('deaths', sa.FLOAT(), nullable=True),
    sa.Column('assists', sa.FLOAT(), nullable=True),
    sa.Column('kda', sa.FLOAT(), nullable=True),
    sa.Column('cs', sa.INTEGER(), nullable=True),
    sa.Column('vision', sa.INTEGER(), nullable=True),
    sa.Column('summoner_spell1', sa.INTEGER(), nullable=True),
    sa.Column('summoner_spell2', sa.INTEGER(), nullable=True),
    sa.Column('item0', sa.INTEGER(), nullable=True),
    sa.Column('item1', sa.INTEGER(), nullable=True),
    sa.Column('item2', sa.INTEGER(), nullable=True),
    sa.Column('item3', sa.INTEGER(), nullable=True),
    sa.Column('item4', sa.INTEGER(), nullable=True),
    sa.Column('item5', sa.INTEGER(), nullable=True),
    sa.Column('item6', sa.INTEGER(), nullable=True),
    sa.Column('game_mode', sa.VARCHAR(), nullable=True),
    sa.Column('game_duration', sa.INTEGER(), nullable=True),
    sa.Column('queue_id', sa.INTEGER(), nullable=True),
    sa.Column('team_position', sa.VARCHAR(), nullable=True),
    sa.Column('participant1_summoner_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant2_summoner_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant3_summoner_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant4_summoner_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant5_summoner_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant6_summoner_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant7_summoner_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant8_summoner_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant9_summoner_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant10_summoner_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant1_champion_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant2_champion_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant3_champion_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant4_champion_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant5_champion_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant6_champion_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant7_champion_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant8_champion_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant9_champion_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant10_champion_name', sa.VARCHAR(), nullable=True),
    sa.Column('participant1_team_id', sa.VARCHAR(), nullable=True),
    sa.Column('participant2_team_id', sa.VARCHAR(), nullable=True),
    sa.Column('participant3_team_id', sa.VARCHAR(), nullable=True),
    sa.Column('participant4_team_id', sa.VARCHAR(), nullable=True),
    sa.Column('participant5_team_id', sa.VARCHAR(), nullable=True),
    sa.Column('participant6_team_id', sa.VARCHAR(), nullable=True),
    sa.Column('participant7_team_id', sa.VARCHAR(), nullable=True),
    sa.Column('participant8_team_id', sa.VARCHAR(), nullable=True),
    sa.Column('participant9_team_id', sa.VARCHAR(), nullable=True),
    sa.Column('participant10_team_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['summoner_puuid'], ['summoners.summoner_puuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
