
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()


class SummonerModel(db.Model):
    __tablename__ = 'summoners'
    summoner_puuid = db.Column(db.String, primary_key=True, unique=True)
    summoner_id = db.Column(db.String)
    summoner_name = db.Column(db.String)
    region = db.Column(db.String)
    last_update = db.Column(db.Integer)
    soloq_rank = db.Column(db.String, default='Unranked')
    soloq_lp = db.Column(db.Integer, default=0)
    soloq_wins = db.Column(db.Integer, default=0)
    soloq_losses = db.Column(db.Integer, default=0)
    soloq_wr = db.Column(db.Integer, default=0)
    flex_rank = db.Column(db.String, default='Unranked')
    flex_lp = db.Column(db.Integer, default=0)
    flex_wins = db.Column(db.Integer, default=0)
    flex_losses = db.Column(db.Integer, default=0)
    flex_wr = db.Column(db.Integer, default=0)
    profile_icon_id = db.Column(db.Integer)
    summoner_level = db.Column(db.Integer)
    
    champion_stats = db.relationship('ChampionStatsModel', backref='summoner', lazy=True)
    matches = db.relationship('MatchModel', lazy=True, backref='summoner')
    
    
class ChampionStatsModel(db.Model):
    __tablename__ = 'champion_stats'
    id = db.Column(db.Integer, primary_key=True)
    summoner_puuid = db.Column(db.String, db.ForeignKey('summoners.summoner_puuid'))
    champion_name = db.Column(db.String)
    matches_played = db.Column(db.Integer)
    wins = db.Column(db.Integer)
    losses = db.Column(db.Integer)
    wr = db.Column(db.Float)
    kda = db.Column(db.Float)
    kills = db.Column(db.Integer)
    deaths = db.Column(db.Integer)
    assists = db.Column(db.Integer)
    cs = db.Column(db.Integer)
    
    
class MatchModel(db.Model):
    __tablename__ = 'matches'
    id = db.Column(db.Integer, primary_key=True)
    summoner_puuid = db.Column(db.String, db.ForeignKey('summoners.summoner_puuid'))
    match_id = db.Column(db.String)
    champion_name = db.Column(db.String)
    win = db.Column(db.Integer)
    kills = db.Column(db.Float)
    deaths = db.Column(db.Float)
    assists = db.Column(db.Float)
    kda = db.Column(db.Float)
    cs = db.Column(db.Integer)
    vision = db.Column(db.Integer)
    summoner_spell1 = db.Column(db.Integer)
    summoner_spell2 = db.Column(db.Integer)
    item0 = db.Column(db.Integer)
    item1 = db.Column(db.Integer)
    item2 = db.Column(db.Integer)
    item3 = db.Column(db.Integer)
    item4 = db.Column(db.Integer)
    item5 = db.Column(db.Integer)
    item6 = db.Column(db.Integer)
    participant1_summoner_name = db.Column(db.String)
    participant2_summoner_name = db.Column(db.String)
    participant3_summoner_name = db.Column(db.String)
    participant4_summoner_name = db.Column(db.String)
    participant5_summoner_name = db.Column(db.String)
    participant6_summoner_name = db.Column(db.String)
    participant7_summoner_name = db.Column(db.String)
    participant8_summoner_name = db.Column(db.String)
    participant9_summoner_name = db.Column(db.String)
    participant10_summoner_name = db.Column(db.String)
    participant1_champion_name = db.Column(db.String)
    participant2_champion_name = db.Column(db.String)
    participant3_champion_name = db.Column(db.String)
    participant4_champion_name = db.Column(db.String)
    participant5_champion_name = db.Column(db.String)
    participant6_champion_name = db.Column(db.String)
    participant7_champion_name = db.Column(db.String)
    participant8_champion_name = db.Column(db.String)
    participant9_champion_name = db.Column(db.String)
    participant10_champion_name = db.Column(db.String)
    participant1_team_id = db.Column(db.String)
    participant2_team_id = db.Column(db.String)
    participant3_team_id = db.Column(db.String)
    participant4_team_id = db.Column(db.String)
    participant5_team_id = db.Column(db.String)
    participant6_team_id = db.Column(db.String)
    participant7_team_id = db.Column(db.String)
    participant8_team_id = db.Column(db.String)
    participant9_team_id = db.Column(db.String)
    participant10_team_id = db.Column(db.String)
    game_mode = db.Column(db.String)
    game_duration = db.Column(db.Integer)
    queue_id = db.Column(db.Integer)
    team_position = db.Column(db.String)
    
    # summoner_model = db.relationship('SummonerModel', backref='match_records', overlaps="matches,summoner")
